### ISSUE TITLE
Add option to have just a simple array of texts, that would spread across all columns

### ISSUE THREAD

**Issue by ra100** [ra100/end-credits-gen#2]
Current behaviour is, you need to specify levels deep in per each "row" which data should be displayed. So if you want to add one name in the list spread across multiple columns, you need to move everything.

example now, this is to have names across 3 columns:
```yaml
 -- marginBottom: 128
    fontSize: 50
    columns:
      - align: center
        xOffset: 1024
      - align: center
        xOffset: 2048
      - align: center
        xOffset: 3072
    content:
      - - - name 1
        - - name 2
        - - name 3
      - - - name 4
        - - name 5
        - - name 6
```

it would be much easier if tool supported this format too:

```yaml
 -- marginBottom: 128
    fontSize: 50
    type: spread
    columns:
      - align: center
        xOffset: 1024
      - align: center
        xOffset: 2048
      - align: center
        xOffset: 3072
    content:
      - name 1
      - name 2
      - name 3
      - name 4
      - name 5
      - name 6
```

and would spread automatically those names in all specified columns, as it's much easier then to add or reorder those names.
